---
"$schema": http://json-schema.org/draft-07/schema#
"$id": http://example.com/root.json
type: object
title: Audiobook Packaging Specification
required:
- book
- resources
- audio
- playlist
properties:
  book:
    "$id": "#/properties/book"
    type: object
    title: The Book Schema
    required:
      - title
      - abridgement
      - author
      - narrator
      - copyright
      - isbn13
      - cover
      - credits
    optional:
      - subtitle
      - version
      - modified
      - license
      - resources
    properties:
      title:
        "$id": "#/properties/book/properties/title"
        type: string
        pattern: "^(.*)$"
        title: String to display as the book title
        examples:
          - The Story of a Specification
      subtitle:
        "$id": "#/properties/book/properties/subtitle"
        type: string
        pattern: "^(.*)$"
        title: Optional subtitle for the book
        examples:
          - From nothing, to something
      abridgement:
        "$id": "#/properties/book/properties/abridgement"
        type: string
        pattern: "^(.*)$"
        title: Book Abridgement
        examples:
          - Unabridged
          - Abridged
          - Other
      author:
        "$id": "#/properties/book/properties/author"
        type: string
        pattern: "^(.*)$"
        title: String to display as the "Author"
        examples:
          - Geoff Jukes and Others
      narrator:
        "$id": "#/properties/book/properties/narrator"
        type: string
        pattern: "^(.*)$"
        title: String to display as the "Narrator"
        examples:
          - Geoff Jukes
      copyright:
        "$id": "#/properties/book/properties/copyright"
        type: string
        pattern: "^(.*)$"
        title: Copyright Statement
        examples:
          - Blackstone Publishing, Inc.
      isbn13:
        "$id": "#/properties/book/properties/isbn13"
        type: string
        pattern: "^([0-9]){13}$"
        title: The Book ISBN-13
        examples:
          - '9781234567890'
      cover:
        "$id": "#/properties/book/properties/cover"
        type: string
        pattern: "^/(.*)$"
        title: Reference Key for Resource File to use as the cover
        examples:
          - "/cover.jpg"
      version:
        "$id": "#/properties/book/properties/version"
        type: string
        pattern: "^(.*)$"
        title: Product Version Reference
        examples:
          - a02291caf068b252c6ba899cf6f13cf3
        pattern: "^(.*)$"
      modified:
        "$id": "#/properties/book/properties/modified"
        type: string
        format: date-time
        title: Product Modified Timestamp
        examples:
          - '2012-08-14T16:49:59+00:00'
      license:
        "$id": "#/properties/book/properties/license"
        type:
          - string
          - 'null'
        pattern: "^(.*)$"
        title: Decryption Key
      credits:
        "$id": "#/properties/book/properties/credits"
        type: object
        title: Book Credits
        patternProperties:
          "^(.*)$":
            "$id": "#/properties/book/properties/credits/patternProperties"
            type: array
            title: Name of Credit to diaply (Author/Narrator/etc )
            items:
              "$id": "#/properties/book/properties/credits/patternProperties/items"
              type: string
              title: The Items Schema
              default: ''
              examples:
                - Geoff Jukes
              pattern: "^(.*)$"
  resources:
    "$id": "#/properties/resources"
    type: object
    title: Resources Collection
    patternProperties:
      "^/(.*)$":
        "$id": "#/properties/resources/patternProperties"
        type: object
        title: Resource File
        required:
          - source
          - label
          - mimetype
        optional:
          - md5
          - modified
          - size
        properties:
          source:
            "$id": "#/properties/resources/properties/source"
            type: string
            format: uri-reference
            title: Where to fetch the file from
            examples:
              - http://example.org/cover.jpg
          label:
            "$id": "#/properties/resources/properties/label"
            type: string
            pattern: "^(.*)$"
            title: Freindly Label for the file
            default: ''
            examples:
              - The Story of a Specification (Unabridged)
          md5:
            "$id": "#/properties/resources/properties/md5"
            type: string
            pattern: "^[a-zA-Z0-9]{32}$"
            title: File MD5
            examples:
              - 06f33a03629a38129cfdfc46be2256c5
          mimetype:
            "$id": "#/properties/resources/properties/mimetype"
            type: string
            pattern: "^[a-z]+/[a-z]+$"
            title: File Mimetype
            default: ''
            examples:
              - image/jpeg
          modified:
            "$id": "#/properties/resources/properties/modified"
            type: string
            format: date-time
            title: File Modified ISO Timestamp
            examples:
              - '2012-08-10T15:39:57+00:00'
          size:
            "$id": "#/properties/resources/properties/size"
            type: integer
            title: File Size in Bytes
            examples:
              - 123456789
  audio:
    "$id": "#/properties/audio"
    type: object
    title: Audio Collection
    patternProperties:
      "^/(.*)$":
        "$id": "#/properties/audio/patternProperties"
        type: object
        title: Audio File
        required:
          - length
        optional:
          - source
          - md5
          - modified
          - size
          - license
        properties:
          source:
            "$id": "#/properties/audio/properties/source"
            type: string
            format: uri-reference
            title: Where to fetch the file from
            examples:
              - http://example.org/cover.jpg
          modified:
            "$id": "#/properties/audio/properties/modified"
            type: string
            format: date-time
            title: File Modified ISO Timestamp
            examples:
              - '2012-08-10T15:39:57+00:00'
          size:
            "$id": "#/properties/audio/properties/size"
            type: integer
            title: File Size in Bytes
            examples:
              - 123456789
          length:
            "$id": "#/properties/audio/properties/length"
            type: number
            title: Track length in seconds
            examples:
              - 3336.3330416666668
          license:
            "$id": "#/properties/audio/properties/license"
            type:
              - string
              - 'null'
            pattern: "^(.*)$"
            title: Decryption Key
  playlist:
    "$id": "#/properties/playlist"
    type: array
    minItems: 1
    title: The Playlist
    items:
      "$id": "#/properties/playlist/items"
      type: object
      title: The Items Schema
      optional:
      - label
      - style
      - indent
      - stylesheet
      - contents
      properties:
        label:
          "$id": "#/properties/playlist/items/properties/label"
          type: string
          pattern: "^(.*)$"
          title: Optional label for this playlist
          examples:
            - Part One
            - Chapter 1
            - Preface
        stylesheet:
          "$id": "#/properties/playlist/items/properties/stylesheet"
          type: string
          pattern: "^(\\w+)(.css)$"
          title: Stylesheet to use for this playlist
          examples:
            - playlist.css
        style:
          "$id": "#/properties/playlist/items/properties/style"
          type: string
          pattern: "^(.*)$"
          title: Default Style for labels in this list
          examples:
            - book-section
        indent:
          "$id": "#/properties/playlist/items/properties/indent"
          type: integer
          title: Display Indent for the label, and base-indent for all contents
          default: 0
        contents:
          "$id": "#/properties/playlist/items/properties/contents"
          type: array
          minItems: 1
          title: Playlist items
          items:
            "$id": "#/properties/playlist/items/properties/contents/items"
            type: object
            title: Playlist Item
            required:
              - label
            optional:
              - audio
              - label
              - audio
              - indent
              - style
            properties:
              label:
                "$id": "#/properties/playlist/items/properties/contents/items/properties/label"
                type: string
                pattern: "^(.*)$"
                title: Label to display for this item
                examples:
                  - In the Beginning
              audio:
                "$id": "#/properties/playlist/items/properties/contents/items/properties/audio"
                type: string
                pattern: "^(.*)$"
                title: Audio to use for this item
                examples:
                  - "/6729-001.m4a"
              indent:
                "$id": "#/properties/playlist/items/properties/contents/items/properties/indent"
                type: integer
                title: Display Indent for this label, offset from Playlist indent
                default: 0
              style:
                "$id": "#/properties/playlist/items/properties/contents/items/properties/style"
                type: string
                pattern: "^(.*)$"
                title: Playlist CSS style reference
              resources:
                "$id": "#/properties/playlist/items/properties/contents/items/properties/resources"
                type: array
                title: Resource files associated with this playlist item
                items:
                  "$id": "#/properties/playlist/items/properties/contents/items/properties/resources/item"
                  type: string
                  pattern: "^(.*)$"